"""File exclusion logic — patterns, binary detection, generated file detection."""

import fnmatch
import os
from pathlib import Path
from typing import List

# Default exclude patterns — comprehensive list for clean inventory
DEFAULT_EXCLUDES = [
    # Test directories and files
    '*_test.*', 'test_*', '*_mock.*', 'mock_*', '*_spec.*',
    '__tests__/', 'tests/', 'test/', 'spec/', 'testing/',
    'fixtures/', '__fixtures__/', 'testdata/', 'test-data/',

    # Dependencies and vendor code
    'node_modules/', 'vendor/', 'third_party/', 'third-party/',
    'external/', 'deps/', 'dependencies/',

    # Python virtual environments and caches
    'venv/', '.venv/', 'env/', '.env/', 'virtualenv/',
    '__pycache__/', '.pytest_cache/', '.tox/', '.eggs/',
    '*.egg-info/', 'site-packages/',

    # Build outputs
    'dist/', 'build/', 'target/', 'out/', 'output/',
    'bin/', 'obj/', 'cmake-build-*/',

    # Version control
    '.git/', '.svn/', '.hg/', '.bzr/',

    # IDE and editor
    '.idea/', '.vscode/', '.vs/', '*.swp', '*.swo',

    # Generated/minified files
    '*.min.js', '*.min.css', '*.bundle.js', '*.bundle.css',
    '*.generated.*', '*.auto.*', '*_generated.*',
    '*_pb2.py', '*_pb2_grpc.py',  # Protobuf
    '*.pb.go', '*.pb.cc',  # Protobuf
    'generated/', 'gen/', 'autogen/',

    # Documentation
    'docs/', 'doc/', 'documentation/',

    # Examples and samples
    'examples/', 'example/', 'samples/', 'sample/', 'demo/',
]

# Markers that indicate a file is auto-generated (check first few lines)
GENERATED_MARKERS = [
    'auto-generated', 'autogenerated', 'automatically generated',
    'do not edit', 'do not modify', 'generated by', 'generated from',
    '@generated', '// code generated', '# generated', '/* generated',
    'this file was generated', 'machine generated',
]


def is_binary_file(filepath: Path, sample_size: int = 8192) -> bool:
    """Check if file is binary by looking for null bytes."""
    try:
        with open(filepath, 'rb') as f:
            chunk = f.read(sample_size)
            return b'\x00' in chunk
    except (IOError, OSError):
        return True  # Treat unreadable as binary


def is_generated_file(content: str, check_lines: int = 10) -> bool:
    """Check if file appears to be auto-generated."""
    lines = content.split('\n', check_lines)[:check_lines]
    header = '\n'.join(lines).lower()

    for marker in GENERATED_MARKERS:
        if marker in header:
            return True
    return False


def should_exclude(filepath: str, exclude_patterns: List[str]) -> bool:
    """Check if file should be excluded based on patterns.

    Returns True if the file matches any exclusion pattern.
    """
    filepath_lower = filepath.lower()
    path_parts_lower = filepath_lower.split(os.sep)

    for pattern in exclude_patterns:
        pattern_lower = pattern.lower()
        # Directory pattern (ends with /)
        if pattern.endswith('/'):
            dir_name = pattern_lower[:-1]
            if dir_name in path_parts_lower:
                return True
        # Glob pattern
        elif '*' in pattern:
            if fnmatch.fnmatch(os.path.basename(filepath_lower), pattern_lower):
                return True
            if fnmatch.fnmatch(filepath_lower, pattern_lower):
                return True
        # Exact filename or path segment match
        elif pattern_lower in path_parts_lower or pattern_lower == os.path.basename(filepath_lower):
            return True

    return False


def match_exclusion_reason(filepath: str, exclude_patterns: List[str]) -> tuple:
    """Like should_exclude but returns (excluded: bool, reason, pattern_matched).

    Used for exclusion recording in the inventory.
    """
    filepath_lower = filepath.lower()
    path_parts_lower = filepath_lower.split(os.sep)

    for pattern in exclude_patterns:
        pattern_lower = pattern.lower()
        if pattern.endswith('/'):
            dir_name = pattern_lower[:-1]
            if dir_name in path_parts_lower:
                return True, "pattern_match", pattern
        elif '*' in pattern:
            if fnmatch.fnmatch(os.path.basename(filepath_lower), pattern_lower):
                return True, "pattern_match", pattern
            if fnmatch.fnmatch(filepath_lower, pattern_lower):
                return True, "pattern_match", pattern
        elif pattern_lower in path_parts_lower or pattern_lower == os.path.basename(filepath_lower):
            return True, "pattern_match", pattern

    return False, None, None
